/* This is file is generated by MCAssetTool.  Do not edit */
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
 
[System.Serializable]
public class mcSearchTags
{
	public int tagID;
	public enum eSearchTags
	{
		Main_0,
			Beef_1,
			Veggies_1,
			Chicken_1,
			Fish_1,
				PorkChops_2,
		Appetizer_0,
			Soup_1,
			Bread_1,
				HotSourdough_2,
		Desert_0,
		ColdDrinks_0,
		HotDrinks_0,
		Plates_0,
		PlaceMats_0,
		Cutlery_0,
		CenterPieces_0,
	}
	public eSearchTags eTag = eSearchTags.Main_0;
}
