/* This is file is generated by MCAssetTool.  Do not edit */
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
 
[System.Serializable]
public class mcSearchTags
{
	public enum eSearchTags
	{
		Main_0,
			Pizza_1,
			Veggies_1,
			Chicken_1,
			Pancakes_1,
		Appetizer_0,
			Bread_1,
		Desert_0,
			Dounut_1,
			Icecream_1,
			Cookie_1,
		ColdDrinks_0,
			Beer_1,
			Wine_1,
			Mix_1,
		HotDrinks_0,
			Tea_1,
		Plates_0,
			Dinner_1,
		PlaceMats_0,
			Carbon_1,
		Cutlery_0,
			Knife_1,
			Fork_1,
			Spoon_1,
		CenterPieces_0,
			Vase_1,
			Candle_1,
	}
 
	public eSearchTags eTag = eSearchTags.Main_0;
}
