/* This is file is generated by MCAssetTool.  Do not edit */
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
 
[System.Serializable]
public class mcSearchTags
{
	public enum eSearchTags
	{
		Main_0 = 1000,
			Pizza_1 = 1100,
			Veggies_1 = 1200,
			Chicken_1 = 1300,
			Pancakes_1 = 1400,
		Appetizer_0 = 2000,
			Bread_1 = 2100,
		Desert_0 = 3000,
			Donut_1 = 3100,
			Icecream_1 = 3200,
				Berry_2 = 3202,
				Coco_2 = 3204,
			Cookie_1 = 3300,
		ColdDrinks_0 = 4000,
			Beer_1 = 4100,
			Wine_1 = 4200,
			Mixed_1 = 4300,
		HotDrinks_0 = 5000,
			Tea_1 = 5100,
		Plates_0 = 6000,
			Dinner_1 = 6100,
		PlaceMats_0 = 7000,
			Carbon_1 = 7100,
		Cutlery_0 = 8000,
			Knife_1 = 8100,
			Fork_1 = 8200,
			Spoon_1 = 8300,
		CenterPieces_0 = 9000,
			Vase_1 = 9100,
			Candle_1 = 9200,
	}
 
	public eSearchTags eTag = eSearchTags.Main_0;
}
